// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_hZhaovQ-JcX98LSIuCXomoF2FNMica4',
    appId: '1:585059466120:web:0f6b83bfafccc3e2a9983d',
    messagingSenderId: '585059466120',
    projectId: 'ifriend-9dbd7',
    authDomain: 'ifriend-9dbd7.firebaseapp.com',
    storageBucket: 'ifriend-9dbd7.firebasestorage.app',
    measurementId: 'G-K0SYM8X2HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD19OL1SAMhS8C6RyCPKRgFujaeI4DYTjY',
    appId: '1:585059466120:android:c2022dfe75de2bd5a9983d',
    messagingSenderId: '585059466120',
    projectId: 'ifriend-9dbd7',
    storageBucket: 'ifriend-9dbd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALninBelYkZSZivzb8i7_uG6DHH3s7bPc',
    appId: '1:585059466120:ios:336e82379fb115caa9983d',
    messagingSenderId: '585059466120',
    projectId: 'ifriend-9dbd7',
    storageBucket: 'ifriend-9dbd7.firebasestorage.app',
    iosClientId: '585059466120-5edhqc4fmkm9bltleff20hnirto3sjid.apps.googleusercontent.com',
    iosBundleId: 'com.example.ifriendApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALninBelYkZSZivzb8i7_uG6DHH3s7bPc',
    appId: '1:585059466120:ios:336e82379fb115caa9983d',
    messagingSenderId: '585059466120',
    projectId: 'ifriend-9dbd7',
    storageBucket: 'ifriend-9dbd7.firebasestorage.app',
    iosClientId: '585059466120-5edhqc4fmkm9bltleff20hnirto3sjid.apps.googleusercontent.com',
    iosBundleId: 'com.example.ifriendApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_hZhaovQ-JcX98LSIuCXomoF2FNMica4',
    appId: '1:585059466120:web:e8e6c113bc272434a9983d',
    messagingSenderId: '585059466120',
    projectId: 'ifriend-9dbd7',
    authDomain: 'ifriend-9dbd7.firebaseapp.com',
    storageBucket: 'ifriend-9dbd7.firebasestorage.app',
    measurementId: 'G-YS4087S16X',
  );

}